spring:
  application:
    name: booking-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}   # profile actif par d√©faut local

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour
  refresh-expiration: 604800000 # 7 days
