spring:
  application:
    name: booking-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}   # profile actif par d√©faut dev

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:404E6352...}
  expiration: 3600000
  refresh-expiration: 604800000
